### ISSUE TITLE
/home/mohit.joshi/pstress_ps/src/third_party/inih++/lib/ini.c:77:5: error: ‘__builtin_strncpy’ output may be truncated copying 49 bytes from a string of length 199 [-Werror=stringop-truncation]    77 |   strncpy(dest, src, size);

### ISSUE THREAD

**Issue by mohitj1988** [benhoyt/inih#104]
Hi, 
    I am using gcc latest version 10.1.0 and using the latest version inih (inih-r49) .
    I am getting errors during make

In file included from /usr/include/string.h:633,
                 from /home/mohit.joshi/pstress_ps/src/third_party/inih++/lib/ini.c:20:
In function ‘strncpy0’,
    inlined from ‘ini_parse_stream’ at /home/mohit.joshi/pstress_ps/src/third_party/inih++/lib/ini.c:199:17:
/home/mohit.joshi/pstress_ps/src/third_party/inih++/lib/ini.c:77:5: error: ‘__builtin_strncpy’ output may be truncated copying 49 bytes from a string of length 199 [-Werror=stringop-truncation]
   77 |     strncpy(dest, src, size - 1);
      |     ^~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [src/third_party/inih++/lib/CMakeFiles/inih++.dir/ini.c.o] Error 1
make[1]: *** [src/third_party/inih++/lib/CMakeFiles/inih++.dir/all] Error 2
make: *** [all] Error 2

Please fix this or suggest a work-around until this gets fixed

**Comment by benhoyt** [comment]
Hmm, this has come up a couple of times (https://github.com/benhoyt/inih/pull/91 and https://github.com/benhoyt/inih/issues/90), so I should really get to the bottom of it and fix it. I still believe the code is doing the right thing, but maybe I need to change to `memcpy` to avoid the warning/error. I'll dig into it further in the next week or so.

**Comment by mohitj1988** [comment]
Thanks. I will wait for you to come to a conclusion.

**Comment by benhoyt** [comment]
That commit should fix it. Can you please verify, and if so, I'll tag a release?

**Comment by mohitj1988** [comment]
Hello,
Using memcpy instead of strncpy works fine! Please go ahead and tag a release.
Thank you!

**Comment by benhoyt** [comment]
Done, thanks! https://github.com/benhoyt/inih/releases/tag/r50

**Comment by benhoyt** [comment]
Unfortunately the straight switch to memcpy introduced a "read from invalid memory" issue. Fixed with https://github.com/benhoyt/inih/releases/tag/r51 in a way that hopefully avoids the gcc warning as well.
