### ISSUE TITLE
Include guard uses a reserved identifier

### ISSUE THREAD

**Issue by HeroicKatora** [benhoyt/inih#111]
The identifier chosen for the include guard (`__INI_H__`, `__INIREADER_H__`) is reserved in both C and C++. The rules for [C according to cpp reference](https://en.cppreference.com/w/c/language/identifier):

> 3) All identifiers that begin with an underscore followed by a capital letter or by another underscore (these reserved identifiers allow the library to use numerous behind-the-scenes non-external macros and functions)

And the rules [for C++](https://en.cppreference.com/w/cpp/language/identifiers) are somewhat stricter:

> the identifiers with a double underscore *anywhere* are reserved;
> the identifiers that begin with an underscore followed by an uppercase letter are reserved; 

To be strictly standard conformant, a different identifier may be chose, for example the pair `INIH_INIH_H`, `INIH_INIREADER_H`.

**Comment by benhoyt** [comment]
Thanks for the note. Fixed in commit https://github.com/benhoyt/inih/commit/d3eda4f60b95efc9ace14b05c8115549f7c0c402
