### ISSUE TITLE
Possible to save data?

### ISSUE THREAD

**Issue by DanielMoura79** [benhoyt/inih#115]
OK I´m read the data from INI file. Very fine.
Is possible to save information using INIH?

**Comment by benhoyt** [comment]
No, there are no library functions to do this -- inih is reading/parsing only. However, writing configs is generally the easy part. You could do it with (f)printf. Something like:

```c
fprintf(f,
    "[user]\n"
    "name = %s\n"
    "email = %s\n",
    name, email);
```
