### ISSUE TITLE
array in ini file for ini parser stream to parse

### ISSUE THREAD

**Issue by chienhsinlin** [benhoyt/inih#120]
Hi!:

I have an array in a ini file like

[section1]

key1 = value1
key2 = value2
.....
lut_table =
1, 2, 3, 4, 5, 6, 7, 8, 
9, 10, 11, 12, 13, 14, 15, 16
......

In the structure, it is defined as
struct {
...
    int lut_table[16];
}
for(i=0; i<16; i++)
   pconfig.lut_table[i] = atoi[multi_value] something?

Can I implement something in the ini_parse_stream to read values for this array? any suggestions? Or something similar  like simpleIni to have a key whic has multivalues?

**Comment by benhoyt** [comment]
Hi @chienhsinlin, there's no special provision for this in inih itself, but you can definitely parse comma-separated values in the handler yourself -- use something like `strchr` or `strtok` to find the `','` (comma) separators.

If the values for one key are spread across multiple lines, you'll also want to set `INI_ALLOW_MULTILINE` to `1`. This works like Python's `configparser` multi-line values -- subsequent values have to be indented with whitespace. For example:

```
[section]
lut_table = 1, 2, 3, 4, 5, 6, 7, 8,
            9, 10, 11, 12, 13, 14, 15, 16
```

Then you'll receive two separate calls to your handler function with the same section and key name, and you'll need to save the last `lut_table` array index in a global or something like that.

Hope that helps!

**Comment by chienhsinlin** [comment]
Thanks a lot, It works now after using strtok in the handler to parse each line and tokenize strings with delimiter.

**Comment by chienhsinlin** [comment]
Something like that. as you said idx is global variable. 
idx = 0; // as global variable. 
```
        tok = strtok((char *)value,",");
        pconfig.lut[idx] = atoi(tok);
        while(tok!=NULL) {
            idx++;
            tok =strtok(NULL," ,");
            if(tok!= NULL)
                pconfig.lut[idx] = atoi(tok); 
        }
```

**Comment by silly2020** [comment]
> Hi @chienhsinlin, there's no special provision for this in inih itself, but you can definitely parse comma-separated values in the handler yourself -- use something like `strchr` or `strtok` to find the `','` (comma) separators.
> 
> If the values for one key are spread across multiple lines, you'll also want to set `INI_ALLOW_MULTILINE` to `1`. This works like Python's `configparser` multi-line values -- subsequent values have to be indented with whitespace. For example:
> 
> ```
> [section]
> lut_table = 1, 2, 3, 4, 5, 6, 7, 8,
>             9, 10, 11, 12, 13, 14, 15, 16
> ```
> 
> Then you'll receive two separate calls to your handler function with the same section and key name, and you'll need to save the last `lut_table` array index in a global or something like that.
> 
> Hope that helps!

for multiple lines like this, seems it's no longer possible to add comments after the value, and the comments either with # or ; are treated as part of value.  Seems it's not right. Is this an issue?  Thanks.

**Comment by benhoyt** [comment]
Hi @silly2020, do you have `INI_ALLOW_INLINE_COMMENTS` turned off? See `ini.h` for a complete list of settings.

**Comment by silly2020** [comment]
Hi, @benhoyt , thanks for prompt reply.  
I didn't turned off INI_ALLOW_INLINE_COMMENTS, it is 1 and INI_ALLOW_INLINE_COMMENTS is ";".  
Comments start with ";" in subsequent lines are treated as part of value, comments in the line with name is OK.   
Thanks again.

**Comment by benhoyt** [comment]
@silly2020 Thanks for the report. This is an oversight (bug!) in inih, and differs from how Python's `ConfigParser` works. Does the latest `master` version work for you? If so, I'll release this in `r56`.

**Comment by silly2020** [comment]
@benhoyt Yes. I tested again with `master` version and it works for me. Thank you so much!
