### ISSUE TITLE
Investigate more on strncpy0

### ISSUE THREAD

**Issue by smoked-herring** [benhoyt/inih#121]
Hi! :) Thanks for the great library!

I'd like to raise the long-running discussion regarding `strncpy0` back again. With the recent change the implementation of `strncpy0` is just a cycle. This heavily worsened the speed of `strncpy0`. The reason is probably that string copying functions always use arch-optimized algorithms (SSE or AVX) where possible and this way they're always faster that just a cycle.

I profiled my app with callgrind and `callgrind_annotate` on LUbuntu 20.04 with INIH 50 (or so) and 52. I filtered the output of `callgrind_annotate` to show the metrics from `ini.c` only.

50 (the most frequent function call is `find_chars_or_comment()` which is OK for me):
```
 29,032  .../src/ini.c:find_chars_or_comment [/usr/local/lib/libsail.so.0.7.0]
```

52 (we have a new leader: `strncpy0()`):
```
 33,913  .../src/ini.c:strncpy0 [/usr/local/lib/libsail.so.0.7.0]
 29,032  .../src/ini.c:find_chars_or_comment [/usr/local/lib/libsail.so.0.7.0]
```

BTW I don't see any warnings with `strncpy` when I compile without `-pedantic`. GCC is 9.3.0.

**Comment by benhoyt** [comment]
Hmm, yeah, that's unfortunate, isn't it. However, is the performance of this really any issue? I'd be surprised if `.INI` parsing needed to be performance-critical in many applications.

**Comment by jkpubsrc** [comment]
The configuration typically is just read once. The total time required for parsing should be much less than even waiting for the data from disk. Starting the program likely takes 1000x more time than loading and parsing of a configuration. Performance should not be the primary issue here.

**Comment by benhoyt** [comment]
Yeah, I agree with @jkpubsrc -- this change was made for "portability" if you like, and I'd rather not flip back for the sake of eeking out the last bit of performance, as inih is not focused firstly on parsing speed.
