### ISSUE TITLE
pkg-config files have version `undefined`

### ISSUE THREAD

**Issue by maxice8** [benhoyt/inih#123]
This breaks Alpine Linux which rely on `Version: ` to be something usable to automatically generate dependencies for `-dev` packages.

```pkgconfig
prefix=/usr
libdir=${prefix}/lib
includedir=${prefix}/include

Name: inih
Description: simple .INI file parser
Version: undefined
Libs: -L${libdir} -linih
Cflags: -I${includedir}
```

**Comment by benhoyt** [comment]
Unfortunately I'm not familiar with pkg-config (or the meson.build files that I guess generates this). @stephanlachnit, any idea of the best approach here?

**Comment by stephanlachnit** [comment]
This is indeed correct, it used to have a version but this requires an update of `meson.build` on every update, which didn't always happen resulting in wrong versions.

I would just add it downstream (by patching Meson with three lines) if it's important.

**Comment by maxice8** [comment]
Understood, added downstream.
