### ISSUE TITLE
unittest.sh doesn' report that tests succeeded?

### ISSUE THREAD

**Issue by yurivict** [benhoyt/inih#128]
Please consider to add a printout that would assure the user that all tests passed.

Currenlty it doesn't print anything.

**Comment by benhoyt** [comment]
Yeah, it uses what's been called "snapshot testing" -- it doesn't actually check anything, it just writes to the output files, which are then `git diff`'d against the known-good ones committed to git. So the `git diff --exit-code` [in the CI script](https://github.com/benhoyt/inih/blob/master/.github/workflows/tests.yml) is what actually does the pass/fail check.
