### ISSUE TITLE
Error attempting to link against libinih

### ISSUE THREAD

**Issue by chunga2020** [benhoyt/inih#130]
Arch Linux 5.13.4. The install reason for `inih` is "as dependency".

I'm trying to create an ncurses application and use `libinih` for config parsing. My `CFLAGS` variable looks like this: `CFLAGS=-g -O2 -Wall -Wextra -Isrc -DNDEBUG -lncurses -lini`.

`find / -name ini.c 2> /dev/null` returns nothing, so I can't use it for compilation.

**Comment by benhoyt** [comment]
Sorry, I don't have much experience with Linux shared libraries/dependency management. Maybe @stephanlachnit can give you a pointer?

**Comment by stephanlachnit** [comment]
If you want to use inih via the shared library, consider using the package config file (`inih.pc`). If you don't use a build system that can do this for you, you can read more about this here: https://people.freedesktop.org/~dbn/pkg-config-guide.html

Your `CFLAGS` look fine though and you shouldn't need `ini.c`. Is it not compiling or what is the problem? If so, please send a log.

If you want to use some of the compile options of inih, you can't use the shared library and need to grab the source yourself.

**Comment by chunga2020** [comment]
I found the problem. The `CFLAGS` variable has `-lini`, when it should be `linih`. D'oh.
