### ISSUE TITLE
Expected key/section missing error

### ISSUE THREAD

**Issue by distantrainbow** [benhoyt/inih#131]
In current implementation, there's no way to receive indication if some key or section are missing in the config file. Especially, for boolean and real/integer key, whos legal values are all type range.

For instance: in my program I expect for the boolean key `should_I_laugh`.
Suppose the containing section or the key itself is missing, in that case I receive the default value (suppose, `false`) from `GetBoolean()` method and I have no way to know if `should_I_laugh=false` because the key/section is missing or because it is actually set to `false` in the file.

It's a serious drawback in default values implementation, that could lead to unexpected wrong code execution while using those values.

**Comment by benhoyt** [comment]
Hi @distantrainbow, are you aware of the [`HasSection` and `HasValue` methods](https://github.com/benhoyt/inih/blob/4f251f0ff766052c342823dfa52a04f486cc4f94/cpp/INIReader.h#L58-L63), which return true if the given section or key is present? Hopefully those can help in your case.

**Comment by distantrainbow** [comment]
Ohh... I feel quite dumb that I've missed that.
Thanks, it answers the need, of course.

**Comment by benhoyt** [comment]
No worries at all!
