### ISSUE TITLE
Do you have plan to support write feature ?

### ISSUE THREAD

**Issue by hyyoxhk** [benhoyt/inih#132]
Do you have plan to support write feature ?

Thanks

**Comment by benhoyt** [comment]
No, unfortunately I have no plans to include write support in this library (that comes with a lot of its own questions, like whether to support comments, how to represent the sections and values, are they all in memory, etc). In addition, it's very easy to write out an INI file with simple `fprintf(f, "[user]\nemail = %s\n", email)` type calls.
