### ISSUE TITLE
Do you plan support buid with cmake

### ISSUE THREAD

**Issue by aengusjiang** [benhoyt/inih#133]
Cmake is a good across building tool. Do you plan support buid with cmake？

**Comment by benhoyt** [comment]
@aengusjiang Sorry, I don't plan to do this. I personally don't want to keep up with N different build systems. There's already a Meson config file for Meson. See further discussion at https://github.com/benhoyt/inih/pull/105 and https://github.com/benhoyt/inih/pull/97

**Comment by Ryanf55** [comment]
How do you recommend `CMake` users consume this library who want to use the package provided by their distribution? 

From reading some other docs, it appears we should use the pkgconfig file, which appears to be shipped with most distributions.

https://cmake.org/cmake/help/latest/module/FindPkgConfig.html

**Comment by neheb** [comment]
Yes, pkgconfig is the way

Btw if you want to add cmake support, meson supports these two: https://mesonbuild.com/CMake-module.html#cmakewrite_basic_package_version_file

simple example:

```
--- a/meson.build
+++ b/meson.build
@@ -10,6 +10,7 @@ distro_install = get_option('distro_install')
 extra_args = []
 
 if distro_install
+    cmake = import('cmake')
     pkg = import('pkgconfig')
 else
     if not get_option('multi-line_entries')
@@ -82,6 +83,11 @@ lib_inih = library('inih',
 if distro_install
     install_headers('ini.h')
 
+    cmake.write_basic_package_version_file(
+      name : 'inih',
+      version : meson.project_version(),
+    )
+
     pkg.generate(lib_inih,
         name : 'inih',
         description : 'simple .INI file parser',
```

Would simplify inclusion into CMake/Conan but currently the only option is pkgconfig.
