### ISSUE TITLE
how to get all the sections, key-value pairs

### ISSUE THREAD

**Issue by 19504643** [benhoyt/inih#144]
Hello, could you please help, how to get all the section names, key-value pairs

**Comment by benhoyt** [comment]
Hi @19504643 william, that's a fairly general question. What do you want to do with them? Print them out, store them in a data structure, something else? If using the C version you'd have to use a handler that stored the section names and key-value pairs in a data structure, and then use that. If using the C++ version there's no way to get a list of all the section names or key-value pairs, only a way to check whether a section or key exists. (Though the [C++ implementation](https://github.com/benhoyt/inih/blob/master/cpp/INIReader.cpp) shows how you'd use the C version to store things in a data structure.)

**Comment by 19504643** [comment]
supporse we downloaded a very outdated configuration file from somewhere, and some sections or key-value pairs were obsolete, we could recursively traverse the file, get the sections and pairs, and pick up the useful data we needed

**Comment by benhoyt** [comment]
Yes, it sounds like you'd need to make your handler store the section names and key-value pairs in a data structure and traverse that. Sorry, I don't have time to write example code for you right now, but hopefully that explanation and the C++ implementation points you in the right direction.
