### ISSUE TITLE
meason.build distro_install option

### ISSUE THREAD

**Issue by nikitos1550** [benhoyt/inih#146]
Hello!

Why distro_install option disables some amount of customization?
How can we setup custom max_line_length=4096, same time with distro_install option?

**Comment by nikitos1550** [comment]
I think I need explanation of distro_install option, I don't understand it's idea.

A bit more details, why do I am asking, we are using Buildroot and there are standard package https://github.com/buildroot/buildroot/blob/master/package/inih/inih.mk they use distro_install be default, we want customize max_line_length and there are no good way to do it with distro_install option setuped. So maybe we can change (contribute to BR) their default makefile, but I want to understand more about inih meason.build idea.

**Comment by benhoyt** [comment]
I actually know very little (read: 0) about meson, so you may have to do some reading at https://mesonbuild.com/, or the effective `meson.build` maintainer for inih, @stephanlachnit, may be able to point you in the right direction too.

**Comment by stephanlachnit** [comment]
> Why distro_install option disables some amount of customization?

It's actually very simple: it is mainly for distribution to build a shared library. If every distro starys using random configs, there is no point in having a shared library since it isn't reliable.

As far as I got your context (somehiny embedded), I would just patch this downstream, *if* you really need it.

**Comment by eli-schwartz** [comment]
> A bit more details, why do I am asking, we are using Buildroot and there are standard package https://github.com/buildroot/buildroot/blob/master/package/inih/inih.mk they use distro_install be default, we want customize max_line_length and there are no good way to do it with distro_install option setuped. So maybe we can change (contribute to BR) their default makefile, but I want to understand more about inih meason.build idea.

But even then, the question becomes: why would buildroot decide to distribute pre-built copies of inih which use those customizations?

Customizations require recompiling with preferred options. So it is best done when you include inih in your project as a vendored dependency, for example as a Meson subproject via `meson wrap install inih`

**Comment by benhoyt** [comment]
Thanks @stephanlachnit and @eli-schwartz. Going to close this issue for now.
