### ISSUE TITLE
Duplicate keys cause a trailing \n to be appended?

### ISSUE THREAD

**Issue by Laro88** [benhoyt/inih#150]
Disclaimer. I don't know if this is fixed as I can't see which version is in the project I am messing with, sorry - so it might have been fixed anthough I could not find the issue mentioned.

This causes a trailing \n to be appended in the string returned when getting key "ip1" in "IPNumbers".

[IPNumbers]
ip1=192.168.20.188
ip1=
ip2=

Get GetString gives me a "192.168.20.188\n" - and it originates from handling the ip1= that is not commented out.

It is on the windows platform and the file is saved with unix style line endings.

**Comment by benhoyt** [comment]
This is sort of a "feature" of how ini.c passes values to the handler, and for multi-line values (where the subsequent line is indented) comes through to the C++ handler with the same section and key name, and we stick a `\n` between the lines. The same happens for duplicate keys.

I don't think I'll change this behaviour at this stage. For what it's worth, Python `configparser` raises an exception for this case by default (though you can set `strict=False`). So I'd recommend just avoiding the duplicate line in your config file. Or if that's not possible, you'll have to write your own value handler that does what you want on duplicate keys.
