### ISSUE TITLE
Add support for UTF-16

### ISSUE THREAD

**Issue by flysand7** [benhoyt/inih#158]
I have a file with UTF-16 BOM, and it seems like the parser is getting stuck on it.

**Comment by benhoyt** [comment]
Do you mean UTF-8 BOM? (inih doesn't support UTF-16 at all.) `inih` should handle that by default. Se https://github.com/benhoyt/inih/blob/4e618f77d4bae216865c5abd972d99b1ba5031e2/ini.c#L160-L166 and note that the default for `INI_ALLOW_BOM` is 1 if it's not set.

**Comment by flysand7** [comment]
Yeah that's a bummer.

**Comment by benhoyt** [comment]
No, I don't think that's a good idea for a minimal library like this. You're welcome to fork it, but I won't be including that here. UTF-16 is pretty legacy at this point, and UTF-8 is becoming / has become the defacto standard for interchange files like this. I'm surprised you have UTF-16 `.ini` files lying around? What's your context or use case?

**Comment by benhoyt** [comment]
I see -- interesting. Unfortunately I'd rather not support UTF-16 in this repo (probably would mean lots more `#ifdef`s and complexity I don't want to support). However, feel free to fork this and add UTF-16 mode.
