### ISSUE TITLE
Undefined symbol when linking with LLD

### ISSUE THREAD

**Issue by ViNi-Arco** [benhoyt/inih#167]
Hi, I'm building with Clang/LLVM/LLD 17.0.6, both the latest release 58 and git master are giving this error:

```c++
ld.lld: error: undefined symbol: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::append(char const*)
>>> referenced by INIReader.cpp
>>>               libINIReader.so.0.p/cpp_INIReader.cpp.o:(INIReader::ValueHandler(void*, char const*, char const*, char const*))
>>> referenced by INIReader.cpp
>>>               libINIReader.so.0.p/cpp_INIReader.cpp.o:(INIReader::ValueHandler(void*, char const*, char const*, char const*))

ld.lld: error: undefined symbol: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::append(char const*, unsigned long)
>>> referenced by INIReader.cpp
>>>               libINIReader.so.0.p/cpp_INIReader.cpp.o:(INIReader::MakeKey(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&))

```

**Comment by benhoyt** [comment]
Ah, the beauty of C++ error messages ... I actually have no idea what this error means. Are you linking to the right C++ runtime libs?

**Comment by ViNi-Arco** [comment]
> Are you linking to the right C++ runtime libs?

Yes, I'm passing libc++ to meson `-D buildtype=plain -Dcpp_args='-O2 -stdlib=libc++'`, removing it allows me to build inih, which makes it use gcc libstdc++, isn't inih incompatible with LLVM libc++?

**Comment by benhoyt** [comment]
Yeah, I guess so! I'm not sure, though -- I'll leave this open in case you get a chance to dig further or somebody else has an idea.

**Comment by neheb** [comment]
@ViNi-Arco I just tried this on Alpine with

```
env CC_LD=lld CXX_LD=lld CC=clang CXX=clang++ CXXFLAGS=-stdlib=libc++ meson a
meson compile -C a
```

compiles

**Comment by neheb** [comment]
Oh this was fixed by https://github.com/benhoyt/inih/pull/165

**Comment by benhoyt** [comment]
@neheb Oh, the linking issue was fixed by making it protected?

**Comment by neheb** [comment]
I mean the error message errors on

```
ValueHandler
MakeKey
```

which are now protected instead of private.

**Comment by neheb** [comment]
I added CI locally to try and see if I can replicate. Nope: https://github.com/neheb/inih/actions/runs/10345239206

I'd close this.

**Comment by benhoyt** [comment]
Thanks. Closing as it seems like #165 fixed this.
