### ISSUE TITLE
Addition of JSON in CycloneDx format

### ISSUE THREAD

**Issue by 3100jisa** [benhoyt/inih#176]
Hello! My project in NIBE AB group is successfully using INIH library.
To fullfil requirements for security, my team is using standard https://cyclonedx.org/ for SBOM (SW Bill Of Materials).
It would be very helpful for me to get properly configured CycloneDx JSON file as part of original INIH respository.
Would you like to prepare this file (not only for me, of course :-) )?
If not, would you be ok with me preparing Pull Request with this file?

Thanks for response!
Jiří

**Comment by 3100jisa** [comment]
Adding that we need to get CPE number first for your INIH project.

I have made same request to CJON repo. For this CPE already exists, see https://nvd.nist.gov/products/cpe/search/results?namingFormat=2.3&keyword=cjson.

**Comment by benhoyt** [comment]
Hi @3100jisa, I'm not particularly interested in learning enough to produce that file, but I would be willing to review a PR if it's simple. Though I'm not sure what an SBOM would consist of, given that inih doesn't have any dependencies outside the C standard library...

**Comment by 3100jisa** [comment]
Thanks for your response. Here is example of such a file.

![image](https://github.com/user-attachments/assets/a6cd56a0-3b79-4f46-98ed-20fe9dec9753)

But key is to get CPE number. Here is example for cJSON library.
https://nvd.nist.gov/products/cpe/detail/E8DA74DA-302A-4934-9335-C00A7857FA40?namingFormat=2.3&orderBy=CPEURI&keyword=cjson&status=FINAL

I will come back to you if I will success with CPE creation. Sorry that I didn't took case before.

**Comment by 3100jisa** [comment]
Closing this topic, sorry for wasting your time.
