### ISSUE TITLE
strncpy error in VS2013

### ISSUE THREAD

**Issue by AgostinoSturaro** [benhoyt/inih#34]
This library seems promising, with tests and all.

When I tried your example in Visual Studio 2013, I got this error

    Error	1	error C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	c:\users\sturaroa\downloads\inih-r30\ini.c	56	1	IniParserTest

I'd rather not use have to set permissive flags just for this bit.

**Comment by benhoyt** [comment]
Hmm, interesting. I believe my use of `strncpy` here is actually safe. What's the typical solution for this? #if to check if you're compiling on Windows, and use strncpy_s or something if so, otherwise regular strncpy?

**Comment by AgostinoSturaro** [comment]
I've researched this, it seems to be VS2013 (and VS2012) complaining about simple things like `fopen` as well, suggesting to use the `_s` versions defined in `TR 24731`, which is an *optional* standard extension of C11.
There's [this option](http://stackoverflow.com/a/121573) to silence it without raising the `_CRT_SECURE_NO_WARNINGS` flag everywhere.

BTW I'm using the cpp wrapper. What happens if the ini file is malformed? Can I detect that with `reader.ParseError()` right after having initialized the reader with `INIReader reader("path")`?

Thanks.

**Comment by andravin** [comment]
@benhoyt yes, and identify windows with #ifdef _WIN32

**Comment by cremno** [comment]
@benhoyt: Yes, it's safe here. A solution could be for users to define `_CRT_SECURE_NO_WARNINGS` (with `/D` or `#define`) by themselves. You could also do it for them.

@AgostinoSturaro: You're mistaken. MS doesn't implement those C11 functions (yet). There are many differences between them.

@andravin: This has nothing to do with Windows itself. There are also other C compilers and standard libraries for Windows.

**Comment by andravin** [comment]
OK, if the strncpy warning is MSVC only, then instead of checking for MS Windows with #ifdef _WIN32, you can check for the MSVC compiler using  #ifdef _MSC_VER

I don't think requiring the user to define _CRT_SECURE_NO_WARNINGS is an acceptable solution.

**Comment by cremno** [comment]
@andravin:

>You could also do it for them.

That's only one line (`#define _CRT_SECURE_NO_WARNINGS`) he has to add before the `#include` directives in `ini.c`

**Comment by benhoyt** [comment]
Okay, I'm happy to add this to ini.c -- I'll do this in the next few days:

    #ifdef _MSC_VER
    #define _CRT_SECURE_NO_WARNINGS 1
    #endif

**Comment by benhoyt** [comment]
I don't have ready access to MSVC right now -- can someone please try adding the above #ifdef dance before the #includes in ini.c and ensure the warning goes away? If so, feel free to send a pull request.

**Comment by benhoyt** [comment]
Fixed in https://github.com/benhoyt/inih/commit/c3458c9e1f536c6dac0327a88cc295e759cef21a and created release r31 with fix: https://github.com/benhoyt/inih/releases/tag/r31
