### ISSUE TITLE
Outdated links

### ISSUE THREAD

**Issue by AgostinoSturaro** [benhoyt/inih#35]
The headers of source files still point to http://code.google.com/p/inih/

    // Read an INI file into easy-to-access name/value pairs.
    // inih and INIReader are released under the New BSD license (see LICENSE.txt).
    // Go to the project home page for more info:
    //
    // http://code.google.com/p/inih/

The [C++ example](https://github.com/benhoyt/inih#c-example) has a link that points to Google Code as well.

`INIReader.cpp` does not have a license header.

BTW are you the original author? The original repository is gone without explanation. You may want to put at least a redirect there.

**Comment by benhoyt** [comment]
Thanks, all links fixed now and license note added to INIReader.cpp.

I am the original author. When I was notified that Google Code was closing down (in a few months) I moved the project to GitHub. You can point the old Google Code project to a new URL, but the redirect is kind of stupid. I have no idea why, but Google Code 301 (permanent) redirects to https://code.google.com/hosting/moved?project=inih, which is a 200 with tiny text saying "View the project at: https://github.com/benhoyt/inih". I don't know why they don't just 301 redirect to the new GitHub URL, but oh well.
