### ISSUE TITLE
inih does not build with -Wcast-qual

### ISSUE THREAD

**Issue by Malizor** [benhoyt/inih#36]
Simply building with:

    gcc -c -Wcast-qual ini.c

Output:
```
ini.c: In function ‘lskip’:
ini.c:42:12: warning: cast discards ‘const’ qualifier from pointer target type [-Wcast-qual]
     return (char*)s;
            ^
ini.c: In function ‘find_char_or_comment’:
ini.c:55:12: warning: cast discards ‘const’ qualifier from pointer target type [-Wcast-qual]
     return (char*)s;
            ^
```

Tested with GCC 4.4 and 4.9 on Debian and Ubuntu.

**Comment by Malizor** [comment]
For the record, I'm integrating inih in a project that is compiled with this flag (among others) and -Werror. This therefore makes the whole build fail.

**Comment by benhoyt** [comment]
Thanks for the report. But hmmm, I don't love this -- the whole point of that cast is to say to the compiler "I know what I'm doing here and really want a `char *`", so this warning seems pretty brutal to me. Those function signatures are "const correct" as they stand, whereas the modified ones are not. Compare to `strchr`, which does the same thing: http://linux.die.net/man/3/strchr

Can you modify your Makefile / project file to disable that warning for `ini.c`? How are other similar functions in your project defined?

**Comment by Malizor** [comment]
Indeed, there is the same problem in strchr from the glibc.

I could remove the warning from the whole project, but it already helped to find issues elsewhere in the past, so I don't think this is the right solution either. There is no similar function in the project.

An alternative is to surround the returns (or the functions or the whole file) by:

    #pragma GCC diagnostic ignored "-Wcast-qual"

and

    #pragma GCC diagnostic pop

But I would not call it beautiful. 

Ultimately, if you don't want to modify anything in inih for this issue, I think I will just remove the warning.

**Comment by benhoyt** [comment]
Thanks. Yes, if `strchr` exhibits the same behaviour, then I'd say it's really an issue with this super-strict warning than the code. So I'd rather not do anything in the inih code, and suggest you work around with something like the above. Sorry!
