### ISSUE TITLE
support ini parse from cstring

### ISSUE THREAD

**Issue by patpatbear** [benhoyt/inih#57]
I get config from a config server, which is char*, and i don't want to save it to file. so i need an API like:
```
int ini_parse_str(const char* str, ini_handler handler, void* user);  
```
so, how about support parse from cstring?

**Comment by benhoyt** [comment]
Hi @patpatbear -- there's already a kind-of way to do this using [ini_parse_stream()](https://github.com/benhoyt/inih/blob/master/ini.h#L57-L60), which takes a function with the same signature as fgets (read one line) that you can use to read from a string or buffer or anywhere you want. See an example provided by someone else that does this for a string: https://github.com/benhoyt/inih/blob/master/ini.h#L57-L60

If this doesn't work for you, please re-open this issue. I'd also be willing to consider cleaning up `ini_buffer_reader` a bit and adding it to inih itself, or a separate file `inih_buffer.c` or something.

**Comment by patpatbear** [comment]
`ini_buffer_reader` is exactly what i needed, I didn't notice it was in the example.

i think it would be nice to add it to inih.

**Comment by patpatbear** [comment]
sounds perfect.
