### ISSUE TITLE
Add support for TIR files

### ISSUE THREAD

**Issue by tbeu** [benhoyt/inih#62]
TIR files for tire data configuration look like INI files, except that they have additional line comments starting with `!` or `$` (as far as I can tell from [sample.tir](https://github.com/tbeu/ExternData/blob/master/ExternData/Resources/Examples/sample.tir)). Could ypu please add support for TIR files.

This works for me, but it would be more useful to configure the line comments at run-time (not at compile-time).
```diff
-        if (*start == ';' || *start == '#') {
+        if (*start == ';' || *start == '#' || *start == '!' || *start == '$') {
             /* Per Python configparser, allow both ; and # comments at the
                start of a line */
         } 
```

**Comment by benhoyt** [comment]
I'm not familiar with TIR files -- where are they used, and is there a spec somewhere? It looks like they also allow `$`-prefixed inline comments. Though that one you can already allow by defining `INI_INLINE_COMMENT_PREFIXES` to `";#!$"`.

I'd rather not add runtime weight (I know it's only a little) as this library is intended primarily for small or embedded systems. However, I'd be happy to add an `INI_START_COMMENT_PREFIXES` define, defaulting to `";#"`, and change the above if statement to:

    if (strchr(INI_START_COMMENT_PREFIXES, *start)) { ... }

Let me know if that sounds reasonable, and you can either add a pull request (with tests), or let me know and I'll add it.

**Comment by tbeu** [comment]
Yes, I would be pretty happy if you could add the INI_START_COMMENT_PREFIXES define. Thanks.

**Comment by benhoyt** [comment]
Done, and added tag/release r41. Thanks!

**Comment by tbeu** [comment]
Perfect. That was fast. Thanks.
