### ISSUE TITLE
ini_parse_string() crash on non-NULL terminated strings

### ISSUE THREAD

**Issue by gdbinit** [benhoyt/inih#68]
ini_parse_string() will crash if string is not NULL terminated. While I guess it is ok to expect NULL terminated strings maybe it would be better to add a check or strdup like function to avoid it?

A quick fuzzer run didn't found any other bugs :-)

**Comment by benhoyt** [comment]
@gdbinit Can you provide any further info here?

**Comment by gdbinit** [comment]
Sorry for delay, vacations got in between.
So I was trying to understand what the hell I was thinking because I had no notes and barely could find the fuzzer code. This makes no sense since strlen is undefined behavior for not NULL terminated strings. I was thinking in the context of libfuzzer where you get the size of the buffer and so could work around the undefined behavior (which I was doing so I could fuzz deeper). So this is essentially C undefined behavior issue and irrelevant. At least the fuzzer couldn't find anything else.
