### ISSUE TITLE
Indentation breaks parsing

### ISSUE THREAD

**Issue by jcrd** [benhoyt/inih#73]
Reproduce with:
```
#include <stdio.h>
#include "inih/ini.h"

int handler(void *user, const char *s, const char *k, const char *v)
{
    printf("%s : %s\n", k, v);
    return 0;
}

int main(int argc, char *argv[])
{
    if (argc > 1)
        ini_parse(argv[1], handler, NULL);
}
```

Input file (lines 2 and 4 are indented with a space):
```
key1=value1
 key2=value2
key3=value3
 key4=value4
```

Output:
```
key1 : value1
key1 : key2=value2
key3 : value3
key3 : key4=value4
```
This was discovered while attempting to parse `.gitconfig` which uses tabs for indentation.

**Comment by benhoyt** [comment]
Hi @jcrd -- inih is actually behaving as documented. By default it parses multi-line values as per Python's ConfigParser, with subsequent indented lines (whether they have an `=` in them or not) being parsed as multi-line values, which comes through as subsequent values with the same key name.

You can see a similar thing in Python's configparser (where `test.ini` is your input file above but with a `[section]` line at the top):

```
>>> import configparser
>>> p = configparser.ConfigParser()
>>> p.read('test.ini')
['test.ini']
>>> list(p['section'])
['key1', 'key3']
>>> p['section']['key1']
'value1\nkey2=value2'
>>> p['section']['key3']
'value3\nkey4=value4'
```

However, if you want to disable parsing of indented multi-line entries, you can compile with `-DINI_ALLOW_MULTILINE=0` (see the `#define` in ini.h).
