### ISSUE TITLE
licensing question

### ISSUE THREAD

**Issue by stevesobol** [benhoyt/inih#74]
This is not a bug report or RFE, but a question:

Instead of building and linking to your code, I'd prefer to include `ini.c`, `ini.h`, `INIReader.cpp` and `INIReader.h` in my own code. Not sure whether this is allowed by the license. Of course, I would include the proper attribution and a copy of the license with my code.

Thanks :)

**Comment by benhoyt** [comment]
Yes, go for it! I think the first part of LICENSE.txt covers that.

> Redistribution and use in source and binary forms, with or without
> modification, are permitted provided that the following conditions are met:
> * Redistributions of source code must retain the above copyright
>   notice, this list of conditions and the following disclaimer.

**Comment by benhoyt** [comment]
@stevesobol Out of interest, what are you using inih for?

**Comment by stevesobol** [comment]
I’m writing a small C++ program that launches a Java app using the JNI Invocation API (a native stub, basically) and will be using inih to read options from an ini file.

**Comment by benhoyt** [comment]
Nice!
