### ISSUE TITLE
Doesn't compile in GUI project

### ISSUE THREAD

**Issue by Valev008** [benhoyt/inih#75]
Hi,
the parser works for me if I use it in console application (in CodeBlocks), but when I add parser files to project with GUI (with WxWidgets), the project doesn't compile - I get a bunch of errors in 'buffer.h' file:

-unknown type name class
-unknown type name namespace
-expected = , ; asm or __attribute__ before ( token
....

All I did was copy the files into project's folder and added them to CodeBlocks project.

Why is it no working?

**Comment by benhoyt** [comment]
Unfortunately I'm not sure what's happening here. Seems like a project setup issue rather than an inih issue -- "buffer.h" isn't actually part of inih. Sorry I can't be of more help. If you're stuck, probably worth asking somewhere like StackOverflow with a few more details.
