### ISSUE TITLE
Feature, read all lines in section

### ISSUE THREAD

**Issue by Laro88** [benhoyt/inih#77]
We use inih and come up with a desire to read all lines in a section so that we can put in some strings (for some radio HW config) inside our config file.
I have some parameters that I need in order inside my application - so an array of char* or ```std::vector<std::string>``` of all lines with content in [Radio] would be awesome.
```
[MQTT]
host=127.0.0.1

[Postgre]
user=postgres dbname=silmarillion

[Radio]
TXfreq=3921
p1=23
p9enabled
sysrebootwatchdog&1
```

**Comment by benhoyt** [comment]
@Laro88 Unfortunately that's not really .INI format anymore -- ini format requires lines with an `=` in the form `field=value`. The syntax you show above is an error in both `inih` as well as Python's `ConfigParser` syntax, on which inih is loosely based.

You'll either need to use INI syntax like `p9=enabled`, or use [multiline syntax](https://docs.python.org/3/library/configparser.html#supported-ini-file-structure) (with subsequent lines indented with whitespace, something like:

```
[Radio]
TXfreq=3921
p1=23
options=
    p9enabled
    sysrebootwatchdog&1
```
