### ISSUE TITLE
Conan package manager for inih

### ISSUE THREAD

**Issue by mohamedghita** [benhoyt/inih#83]
I have written a conan package for inih. Installing and building the library on any platform should be as easy as running:
`conan install inih/44@radalytica/stable
`

The conan package lives on this repo: https://github.com/mohamedghita/conan-inih
The package is also uploaded to a Bintray repo: https://bintray.com/radalytica/conan-radalytica/inih:radalytica

I hope this could be of help to someone :)

**Comment by benhoyt** [comment]
Thanks! I've added a section [Related links](https://github.com/benhoyt/inih/blob/master/README.md#related-links) in the README and linked to it there.
