### ISSUE TITLE
Support for ExtendedInterpolation Environment variables.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [benhoyt/inih#89]
Would be nice to have, but should be an opt-in define or maybe a separate method...
As you would have to find all the \$\{.*\} patterns and call a GetEnvironmentVariable for each then place it in.

**Comment by benhoyt** [comment]
Hi @LiamKarlMitchell -- nice to see a comment from a fellow Kiwi!

As far as interpolation goes, inih is a minimalist library, and I think it's out of scope for what I want inih to be. It's also not hard to achieve outside of inih by running through the parsed file afterwards (or inside the handler) and making the replacements. So I don't think I'll include this feature inside inih. Happy to put an example inside `examples/` and link to it though!
